### ISSUE TITLE
Error when Requesting an Sms 

### ISSUE THREAD

**Issue by Gorock** [sumppen/WhatsApi4J#10]
When i request an sms code  i get this error

Event code_request_failed: phoneNumber=380666386612
Caught exception: There was a problem trying to request the code. Status=fail
net.sumppen.whatsapi4j.WhatsAppException: There was a problem trying to request the code. Status=fail
	at net.sumppen.whatsapi4j.WhatsApi.codeRequest(WhatsApi.java:322)
	at net.sumppen.whatsapi4j.example.ExampleApplication.sendRequest(ExampleApplication.java:147)
	at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:98)

would be nice if i know what im doing wrog

**Comment by akshay-bilani** [comment]
same with me when we send uri request responce status does not right it give fail

**Comment by tawfik90** [comment]
hey whatsapi4j was working with me but now it doesn't work can anyone help me

**Comment by akshay-bilani** [comment]
Code request failed. Reason: no cell routes to send sms for your operator.

**Comment by akshay-bilani** [comment]
when i use https://coderus.openrepos.net/whitesoft/whatsapp_sms link but it
give above msg and i use whatasapi4j it give error
Event code_request_failed: phoneNumber=380666386612
Caught exception: There was a problem trying to request the code.
Status=fail
net.sumppen.whatsapi4j.WhatsAppException: There was a problem trying to
request the code. Status=fail

**Comment by sumppen** [comment]
WhatsApp had modified some details in the registration. 

I’ve modified the code and he request and registration works again
$ java -cp target/dependency/*:target/whatsapi4j-1.0.0-SNAPSHOT.jar net.sumppen.whatsapi4j.example.ExampleApplication xxxxxxxx '’ 'foo’ 'bar'
$ request
Event code_request: phoneNumber=xxxxxxxx
Registration sent: {
  "length": 6,
  "method": "sms",
  "retry_after": 1805,
  "status": "sent"
}
$ Done! Logging out
$ java -cp target/dependency/*:target/whatsapi4j-1.0.0-SNAPSHOT.jar net.sumppen.whatsapi4j.example.ExampleApplication xxxxxxxx '’ 'foo’ 'bar'
$ register
Code: 123456
Event code_register: phoneNumber=xxxxxxxx
{
  "cost": "1.28",
  "currency": "SGD",
  "expiration": 1455075422,
  "kind": "free",
  "login": "xxxxxxxx",
  "price": "$1.28",
  "price_expiration": 1426417037,
  "pw": “yyyyyyyyyyyy=",
  "status": "ok",
  "type": "new"
}
$ Done! Logging out

**Comment by akshay-bilani** [comment]
this project does not contain relative jar file

**Comment by akshay-bilani** [comment]
when i send below link by browser it give responce fail
 https://v.whatsapp.net/v2/code?cc=91&in=**********&lg=hi&lc=IN&method=sms&sim_mcc=404|405|406&sim_mnc=000&token=1d868a124a3a092a2d25ec0ab1530217&id=i%9e%14i%7ca%d8%86%88jp%88%23%b2%b9%0cv%9b%3e%8e


server give responce 
{"status":"fail","reason":"bad_param","param":"sim_mcc"}
