### ISSUE TITLE
Not receiving "from" attribute

### ISSUE THREAD

**Issue by jinfanzon** [sumppen/WhatsApi4J#11]
When running the example of this repo, when I receive a message, the from field is "from="s.whatsapp.net"" without the sender number. What might be wrong?

**Comment by jinfanzon** [comment]
I was able to do this in a MessagePoller class by doing:

List<ProtocolNode> nodes = wa.getMessages();
			Iterator<ProtocolNode> itNodes = nodes.iterator();
			while(itNodes.hasNext()){
				ProtocolNode node = itNodes.next();

and obtaining the message from node.

My question now is, in order to reply. how do I obtain the "from" that is later set in sendMessage together with @s.whatsapp.net

**Comment by jinfanzon** [comment]
Eventhough If the message is received from a group, the from is being set correctly

**Comment by jinfanzon** [comment]
@sumppen I believe the issue is located in KeyStream.cypher. When I send a message from a group the ciphered array starts with : [-6, -1, 12, X, X ... but if it is a direct message the ciphered array is [-6, -1, -121,X,X. 

So then in BinTreeNodeReader. readNibble, the nrOfNibbles is negative, so it does not enter the loop and in consequence the number is not bein displayed in the from field. 

This is what I've found, I'm not sure why when it is group the ciphered array contains 12 and when it is a DM it is -121. If you have the chance to check. Probably the issue is in the RC4, not sure.

**Comment by sumppen** [comment]
I’ll take a look at this as soon as I have some time.

/Kim

**Comment by sumppen** [comment]
Problem was in the readNibble code, and should be fixed now

**Comment by jinfanzon** [comment]
Thanks indeed!
