### ISSUE TITLE
My registered number blocked

### ISSUE THREAD

**Issue by cfathoni** [sumppen/WhatsApi4J#13]
Hi,

I have used whatsapi for a week without a problem. But, today when I tried to start my application it always throw whatsappException which means fail to login. Then I tried to use the registered number on my phone but when I try to connect the number, the message "Your number is no longer allowed" occurred, that means my number was blocked. I do not use it for sending bulk message. So could you help me what makes the number to be blocked by Whatsapp. Btw, when I tried to register other number it works normally. Thanks for your help

**Comment by jinfanzon** [comment]
hi @cfathoni. According to whatsapp terms of use, you'll be banned if: 

* Sending too many messages to users who do not list you in their address books. Make sure that you ask all of your WhatsApp contacts to add your current number to their address books.

*Being blocked by too many people in a short period of time. Make sure you only communicate with people who want to receive messages from you.

*Creating too many groups that contain users who do not list you in their address books. Make sure that you ask all of your WhatsApp contacts to add your current number to their address books.

*Sending the same message to too many people. Use Broadcast Lists to send the same message to your contacts.

There is cuntdown timer and you'll be able to send messages when the timer runs out

Hope it helps!

**Comment by cfathoni** [comment]
Hi jinfanzon,

Thank you for the reply. I am pretty sure that I have not do the list that you have mentioned above. Talking about countdown timer, do you know how long it is?. It's been almost 7 hour that my number cannot log in to whatsapp.

Is it possible that I was blocked due to how I manage to always connect all the time?. In the example, the application will be terminated after idle for several minutes. So I am always trying to reconnect (relogin) whenever it happened to keep my application alive and always available to retrieve the request. Or there is another way to keep it alive?

Thanks for your help :)

**Comment by jinfanzon** [comment]
@cfathoni I'm sorry, but I'm not sure about the cuntdown nor the reason. But for what I read this is what happens:

"72 hours after your account has been been banned, your friends will no longer be able to see you in their Favorites / Select contact lists"

"We may not issue a warning before banning your account. If you think your account was banned by mistake you can email us and we will look into your case."

I believe you should send an email to: support@whatsapp.com.

I've also found a page to raise a ticker, but not sure if it is the official site 
https://whatsapp.zendesk.com/access/unauthenticated#login

Also what I've read is " You will receive a warning message in the app that contains the duration of this temporary ban", didn't you receive it?

**Comment by cfathoni** [comment]
Hi,

I have tried to register another number for my application. It is still running fine for a week. I am pretty curious what makes my old number to be banned. Maybe I should try to email whatsapp in order to know what makes my old number to be banned. @jinfanzon thanks for your support :).
