### ISSUE TITLE
is it possible to recieve images?

### ISSUE THREAD

**Issue by NirHUJI** [sumppen/WhatsApi4J#16]
Hi! 
Thank you very much about the api,  it seems that you have done a lot of great work over there:)
I want to build a whatsApp client that could receive only images and videos (don't need to send anything), so before im starting to dive into your code i wanted to ask you if you already implemented those functions.

**Comment by sumppen** [comment]
Hi

Yes those are implemented and tested

**Comment by NirHUJI** [comment]
thanks for the fast reply!
i forgot to ask about groups- is it possible to recieve messages from groups? (may be it's the same mechanism...i don't know whatsapp architecture yet so im asking just to make sure)

**Comment by sumppen** [comment]
Yes, it's possible to receive messages from groups as well

**Comment by NirHUJI** [comment]
awesome:)
thank you very much!
