### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by tsvetkoff** [sumppen/WhatsApi4J#17]
Hello everyone! I try to use WhatsApi4J but I have some problems.

Description says I should run the program using console command
java -cp target/dependency/*:target/whatsapi4j-1.0.0-SNAPSHOT.jar net.sumppen.whatsapi4j.example.ExampleApplication 358401122333 'mypassword' 'mytestapplication' 'My Test Account'

Having been done this I got Login exception as mentioned at image below:
![default](https://cloud.githubusercontent.com/assets/11502146/6665830/66400db6-cbf7-11e4-8a8e-af8d62af26b5.PNG)
(my version of project is https://github.com/sumppen/WhatsApi4J/commit/33cf3948e73be195ad8d6c3c450002ef873435ec )

So the connection set, but response contains 
failure
    not-authorized /not-authorized
/failure

I need to know if the phone have been registered in WhatsApp. So I check that code invokes web service. I try to use url https://v.whatsapp.net/v2/exist?cc={mycode}&in={myphone} to obtain a identity where mycode and myphone are mine. So response looks like this:  {"status":"created","id":"/zNEZIyuHx1ZnIKSl7txgpwEyUE=","sms_length":6,"voice_length":6} 
(id here is 29char-string)
Next, I try to check account linked this id by:
https://v.whatsapp.net/v2/exist?cc={mycode}&in={myphone}&id=/zNEZIyuHx1ZnIKSl7txgpwEyUE=
So I get {"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6}.

Please, tell me what I do wrong?

**Comment by sumppen** [comment]
The example is just an example. The password ‘mypassword’ is not correct for the account number 358401122333

You need to have your own phone number, which you register using the API. The registration process will return a password for your account

/Kim

**Comment by tsvetkoff** [comment]
Thank you for your early reply!

So If I understand right I need 
1) real phone number 
2) using phone number I will get id like /zNEZIyuHx1ZnIKSl7txgpwEyUE= 
3) using id I will get the password if the "status" will be "ok".
All these things I need pass to WhatsApi constuctor.

Could you say, if 29char-string like {id:"/zNEZIyuHx1ZnIKSl7txgpwEyUE="} is valid identity example? If it is valid - why I got {"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6}?

**Comment by tsvetkoff** [comment]
Thank you, I have solved my problems )

**Comment by vcanilkumar** [comment]
Hi ,

Please let me know the solution for this ?


Regards, Anil

**Comment by NirHUJI** [comment]
vcanilkumar, read the api- you have a register command there. all you need to do is:
1.put your real phone number, choose any identity and any nickname.
2. request confirmation code using the api. 
3. register using the code that had been sent to your phone. (you have a register command in the api).
4. the register command will return you a json object that conatins the key "pw" with your password. use this password for login.

**Comment by vcanilkumar** [comment]
Hi,

Thanks for the response. My issue is with point(2)  where I'm unable to get
the confirmation code on my mobile

Exception :

Event code_request_failed: phoneNumber=<<MyNum>>
Caught exception: There was a problem trying to request the code.
Status=fail
net.sumppen.whatsapi4j.WhatsAppException: There was a problem trying to
request the code. Status=fail
        at net.sumppen.whatsapi4j.WhatsApi.codeRequest(WhatsApi.java:280)
        at
net.sumppen.whatsapi4j.example.ExampleApplication.sendRequest(ExampleApplication.java:187)
        at
net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:129)

Regards, Anil

**Comment by NirHUJI** [comment]
are you using the full phone number with country code?
if your county code for example is 188 and yor phone number is 054-8888888 you need to get rid of the trailing zero and the number should be- 188548888888.
if your phone number is right and it still doesn't work, maybe it's better if you check the contry.cvs file in the resource folder and see if it contains the right information about your country:/

**Comment by vcanilkumar** [comment]
Thanks again.

I don't see issue with the phone number.My country code is 91 (INDIA).For
India it is maintained as "404|405|406" ,looks like incorrect.
I have verified the code in
https://en.wikipedia.org/wiki/Mobile_country_code and find the below
information for my operator and hardcoded as

query.put("sim_mcc","404");
query.put("sim_mnc","086");

40486Vodafone INKarnataka



I'm getting "bad Token" error when I try the below in the browser

https://v.whatsapp.net/v2/code?cc=91&in=
<<MyNumber>>&lg=hi&lc=IN&method=sms&sim_mcc=404&sim_mnc=086&token=b8965a1fabbe9c888db6bbf131139e36&id=QSLlRWIZ169Gbx7bjecASbi7iUg=



Regards, Anil

**Comment by NirHUJI** [comment]
as i can see from the code (and btw- don't confuse me with the code owner:) ), 
in the method codeRequest there is a call  genearate token:
token = generateRequestToken(phone.get("country"), phone.get("phone"));

did you rememer to hardcoded the country code there too?

**Comment by vcanilkumar** [comment]
I do not see the issue with the data in the parameters "token =
generateRequestToken(phone.get("country"), phone.get("phone"));" where I
see data being sent properly

I also tried by hard coding the values, but lo luck :-(


Regards, Anil

**Comment by vcanilkumar** [comment]
Hi ,

started working ..finally !!! Thanks again for your support !!

Regards, Anil

**Comment by NirHUJI** [comment]
great!
maybe it will be better if you tell us exactly how you solved the problem so that other people that are facing the same problem could solve it too

**Comment by sreeramulugouds** [comment]
hi i have taken new updated code ,but i am getting {"status":"fail","reason":"bad_token"} ,i want to generate request code and need to register mobile number but while requesting for code it is giving above error , i used old version that is giving in json reason attribute  old version  and failed ,Please anyone can help me.

**Comment by sreeramulugouds** [comment]
Hi All,
I am facing problem while giving request to generate  request code 
req:: https://v.whatsapp.net/v2/code?cc=91&in=9223188820&lg=hi&lc=IN&method=sms&sim_mcc=000&sim_mnc=000&token=1d8a8a3e0e5fea25b3e2c14369b18ce8&id=%a9j%8f%e5%cc%b1%9b%a6%1cl%08s%d3%91%e9%87%98%2f%bb%d3
repose::
{"status":"fail","reason":"bad_token"}

I am using new whats app code only,please provide if i  miss anything  you.

**Comment by sreeramulugouds** [comment]
bad token exception is coming while calling request for request code.

**Comment by vcanilkumar** [comment]
Hi,

Make sure the method "WhatsApi.generateRequestToken() receiving proper
values of "country code" and "your number" as parameters.

Regards, Anil
