### ISSUE TITLE
Android compotability

### ISSUE THREAD

**Issue by NirHUJI** [sumppen/WhatsApi4J#20]
Hi!
Im using your API for building an Android client, and i have just finished to tweak it so it could work on Android devices. i needed to change the Log library (i found an automatic tool for doing so) and the client library for sending http request because they where not compatible with the Android os. 
as for now i was able to send code request, login with password and poll mesages. 
if you are interested in making your API Android compatible, send me a message and i will explain to you the changes that need to be made (there aren't many changes at all).
Thanks again for your great work!

**Comment by klutzer** [comment]
Have you tried to implement your needs and create a pull request for it?

**Comment by NirHUJI** [comment]
Im working now full power on a different project so i don't have the time to polish my compatible version of the API and pull it. Right now the changes that i made are quite uglly and very android specific...there is still a need for some work to be done in order to making it both android and pc compatible...
when ill finish the first version of my app (hopfully in a couple of weeks from now) ill start cleaning the code for my version of the Api and i will create a pull request. 
I openned this issue just in case that someone has the time to make the changes right now and needs some instructions for how do do it,  or if someone needs a working but ugly version, it could just ask me:)

**Comment by NirHUJI** [comment]
I checked again the parts that needed to be change in order for the api to be compatible and i have two questions:
1. Is there any specific reason for why you are using log4j? 
in order to make the Api compatible with android i need to change slf4j and use the standad jdk logging.

2. in WhatsMediaUploader.class, inside sendData() you have this line:
		Security.addProvider( new com.sun.net.ssl.internal.ssl.Provider());

what does this line do? the android studio give me an error on this line and i can't build the project without commenting it out.

**Comment by sumppen** [comment]
I've used log4j out of habit, but have no issues with moving to slf4j.
So I've updated the code to use slf4j instead.

The addProvider came from some example code I found, and turns out it's not needed, so I've removed it
