### ISSUE TITLE
Add Date field to Message bean

### ISSUE THREAD

**Issue by drenda** [sumppen/WhatsApi4J#29]
I see that there isn't a Date field in BasicMessage or at least on TextMessage. I don't understand why. There is some reason for that?

Now to extract the data field I've to do:
```java
String dataUnixTime = message.getProtocolNode().getAttributes().get("t");
Instant instant = Instant.ofEpochMilli(Long.valueOf(dataUnixTime) * 1000);
LocalDateTime res = LocalDateTime.ofInstant(instant, ZoneId.systemDefault());
log.debug("Message Date -> " + res);
```
Instead would be nice do:
```java
message.getDate();
```

**Comment by klutzer** [comment]
We can implement this, but we have to force use of JodaTime library, to retrurn `message.getDate()` as a DateTime type.

**Comment by drenda** [comment]
You can use java.util.Date if you don't want add external dependency.

Thanks
Il 12/Apr/2015 04:08, "Érico Knapp Lutzer" <notifications@github.com> ha
scritto:

**Comment by sumppen** [comment]
Implemented and tested
