### ISSUE TITLE
request code error- old version

### ISSUE THREAD

**Issue by NirHUJI** [sumppen/WhatsApi4J#36]
When i try to request code im getting this respons:
{"reason":"old_version","status":"fail"}

i googled it and i think the token is needed to be updated but i don't know where should i find the new token. any suggestions?

**Comment by itzikedery** [comment]
+1

**Comment by sumppen** [comment]
I've updated the token, but can't test it myself at the moment

**Comment by NirHUJI** [comment]
sovled!
