### ISSUE TITLE
"Bad token" problem again

### ISSUE THREAD

**Issue by NirHUJI** [sumppen/WhatsApi4J#39]
I have the same problem again...
where do you get the new tokens from?

**Comment by antonu17** [comment]
WhatsApi.java:70
	private static final String RELEASE_TOKEN_CONST = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk";
this should work

**Comment by NirHUJI** [comment]
Thanks a lot!
solved:)
