### ISSUE TITLE
Number block

### ISSUE THREAD

**Issue by Penks** [sumppen/WhatsApi4J#45]
sir after sending a msg to 10 contacts Event disconnected and  my number block . what should id if i want to send a msg to 20 contacts.
please help me

**Comment by elbano** [comment]
Maybe you got blocked from whatsapp for a violation of service, I believe sms spamming is against their terms of service.

**Comment by sumppen** [comment]
As elbano said, most likely you triggered some WhatsApp safeguard. I do not know exactly what triggers they have.
