### ISSUE TITLE
how to use WhatsApi4J?

### ISSUE THREAD

**Issue by dunfrey** [sumppen/WhatsApi4J#46]
I've tried many ways, I read some forums, but I can not even put the example to work. 
How to proceed? How to use WhatsApi4J?

**Comment by elbano** [comment]
Code your own example class, the implementation is easy to use. You can
start by coding a class for the registration and other for login and chat.
The example class is very reusable.

2015-06-08 14:18 GMT-04:30 Dunfrey Pires Aragão <notifications@github.com>:

> I've tried many ways, I read some forums, but I can not even put the
> example to work.
> How to proceed? How to use WhatsApi4J?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sumppen/WhatsApi4J/issues/46>.
>



-- 
--
Elbano Marquez

**Comment by dunfrey** [comment]
The error is: 


--- exec-maven-plugin:1.2.1:exec (default-cli) @ whatsapi4j ---
Usage: ExampleApplication <username> <password> <id> <nick>
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.228s
Finished at: Tue Jun 09 15:01:51 BRT 2015
Final Memory: 6M/112M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project whatsapi4j: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by dunfrey** [comment]
![errowhats](https://cloud.githubusercontent.com/assets/11588256/8066140/560aa89a-0ebc-11e5-8636-b2a28a3e68c8.png)

**Comment by sumppen** [comment]
The username and password are just examples and are not valid. You must provide your own user (phone number) and password. You can register your user using the example application
