### ISSUE TITLE
Bad token problem

### ISSUE THREAD

**Issue by klutzer** [sumppen/WhatsApi4J#51]
I get this when I try to register a new phone number:

```
7 [AWT-EventQueue-0] DEBUG net.sumppen.whatsapi4j.WhatsApi - ID: p%f2i%db7%5d%beqc2%9b%8d%b3%fa%059%92%f8%7b%f5
65 [AWT-EventQueue-0] DEBUG net.sumppen.whatsapi4j.WhatsApi - Request: https://v.whatsapp.net/v2/code?cc=55&in=9999999999&lg=pt&lc=BR&method=sms&sim_mcc=724&sim_mnc=000&token=d93d1152a72ef6fd598f08c2b940fb03&id=p%f2i%db7%5d%beqc2%9b%8d%b3%fa%059%92%f8%7b%f5
1505 [AWT-EventQueue-0] DEBUG net.sumppen.whatsapi4j.WhatsApi - {
 "reason": "bad_token",
 "status": "fail"
}
```

**Comment by klutzer** [comment]
Where I can get this token? What about automatic update in API?

**Comment by elbano** [comment]
Can you write the code invoking the register method, I think you are
missing the IMEI.

2015-06-18 14:44 GMT-04:30 Érico Knapp Lutzer <notifications@github.com>:

> Where I can get this token? What about automatic update in API?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sumppen/WhatsApi4J/issues/51#issuecomment-113262943>.
>



-- 
--
Elbano Marquez

**Comment by klutzer** [comment]
No.. it was woking before.. The API doesn't send the SMS code to register anymore..

**Comment by elbano** [comment]
I assume that with a different number and IMEI.

2015-06-18 15:02 GMT-04:30 Érico Knapp Lutzer <notifications@github.com>:

> No.. it was woking before.. The API doesn't send the SMS code to register
> anymore..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sumppen/WhatsApi4J/issues/51#issuecomment-113266780>.
>



-- 
--
Elbano Marquez

**Comment by klutzer** [comment]
I've already tried.. same problem...

**Comment by elbano** [comment]
Honestly I have only used the api to register one line, and at that moment
it worked, that was a couple of months ago. Maybe whatsapp have stiffen up
their security. Maybe by reverse engineer de .jar of the android release
you will be able to see any new implementation, but going through that app
can be exhausting, has a very intricate architecture.

2015-06-18 15:30 GMT-04:30 Érico Knapp Lutzer <notifications@github.com>:

> I've already tried.. same problem...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sumppen/WhatsApi4J/issues/51#issuecomment-113273738>.
>



-- 
--
Elbano Marquez

**Comment by klutzer** [comment]
The problem might be in the RELEASE_TOKEN_CONST

**Comment by elbano** [comment]
That variable was changed in one of the last commits of the project, I
think, maybe that the variable was a constant before and now is updated
periodically. Is only an assumption...

2015-06-18 16:04 GMT-04:30 Érico Knapp Lutzer <notifications@github.com>:

> The problem might be in the RELEASE_TOKEN_CONST
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sumppen/WhatsApi4J/issues/51#issuecomment-113281803>.
>



-- 
--
Elbano Marquez

**Comment by klutzer** [comment]
The API now...

```java
public class WhatsApi {

    private static final String RELEASE_TOKEN_CONST = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk";
    private static final String RELEASE_TIME = "1419900749520";
    ...
}
```

**Comment by klutzer** [comment]
Could someone try to register a new phone number in API?

**Comment by ctaity** [comment]
i can try register next monday or tuesday

**Comment by sumppen** [comment]
I checked the token from PHP api, and the token was same, but the date was different, so I updated the date.
I also made setters for both token and date, so you can modify those at runtime

**Comment by rahulserver** [comment]
@klutzer does not register. I still get the bad_token issue.

**Comment by klutzer** [comment]
I'd already tried to change the date, but the "bad token" still happen..

**Comment by klutzer** [comment]
The most recent version of the API still appears "bad token" in registration new phone number.

**Comment by klutzer** [comment]
Anyone?

**Comment by mrcel** [comment]
Had the same issue, try WART to retrieve your login credentials (https://github.com/mgp25/WART) until the bug is fixed.

**Comment by klutzer** [comment]
Solved in my pull request.

Thanks

**Comment by mrcel** [comment]
@klutzer Which USER-AGENT are you using now?

**Comment by klutzer** [comment]
see https://github.com/klutzer/WhatsApi4J/blob/master/src/main/java/net/sumppen/whatsapi4j/WhatsApi.java

**Comment by kaank** [comment]
Hi,

Please change this class in whatsappapi.dll 

  class WaToken {
        public static string GenerateToken(string number) {
            string s = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1430860548912" + number;
            byte[] bytes = Encoding.ASCII.GetBytes(s);
            byte[] value = MD5.Create().ComputeHash(bytes);
            return BitConverter.ToString(value).Replace("-", string.Empty).ToLower();
        }
        private static List<byte> GetFilledList(byte item, int length) {
            List<byte> list = new List<byte>();
            for (int i = 0; i < length; i++) {
                list.Add(item);
            }
            return list;
        }
    }
