### ISSUE TITLE
no_route on request

### ISSUE THREAD

**Issue by klutzer** [sumppen/WhatsApi4J#9]
I've tried to run the ExampleApplication, but when I call the request operation, this JSON returns (for any phone number):

{"reason":"no_routes","status":"fail","retry_after":3600}

**Comment by sumppen** [comment]
Hi,

Does the server/pc where you run the application have full internet access and fully working DNS? It sounds a little like it fails to connect to the WhatsApp servers

/Kim

**Comment by klutzer** [comment]
Hi,

Yes, If running tests with python Yowsup API works..

**Comment by akshay-bilani** [comment]
When i request an sms code i get this error
Event code_request_failed: phoneNumber=**********
Caught exception: There was a problem trying to request the code. Status=fail
net.sumppen.whatsapi4j.WhatsAppException: There was a problem trying to request the code. Status=fail
at net.sumppen.whatsapi4j.WhatsApi.codeRequest(WhatsApi.java:322)
at net.sumppen.whatsapi4j.example.ExampleApplication.sendRequest(ExampleApplication.java:147)
at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:98)
would be nice if i know what im doing wrog

**Comment by akshay-bilani** [comment]
dear sir can u give ur email id

**Comment by sumppen** [comment]
WhatsApp had modified some details in the registration. 

I’ve modified the code and he request and registration works again
$ java -cp target/dependency/*:target/whatsapi4j-1.0.0-SNAPSHOT.jar net.sumppen.whatsapi4j.example.ExampleApplication xxxxxxxx '’ 'foo’ 'bar'
$ request
Event code_request: phoneNumber=xxxxxxxx
Registration sent: {
  "length": 6,
  "method": "sms",
  "retry_after": 1805,
  "status": "sent"
}
$ Done! Logging out
$ java -cp target/dependency/*:target/whatsapi4j-1.0.0-SNAPSHOT.jar net.sumppen.whatsapi4j.example.ExampleApplication xxxxxxxx '’ 'foo’ 'bar'
$ register
Code: 123456
Event code_register: phoneNumber=xxxxxxxx
{
  "cost": "1.28",
  "currency": "SGD",
  "expiration": 1455075422,
  "kind": "free",
  "login": "xxxxxxxx",
  "price": "$1.28",
  "price_expiration": 1426417037,
  "pw": “yyyyyyyyyyyy=",
  "status": "ok",
  "type": "new"
}
$ Done! Logging out

**Comment by huchdadiya** [comment]
Hi sumppen,
   Can you please confirm that this is working today also? because I am not able to register for sending messages.
  Actually there is no response coming from v.whatsapp.net when I try to hit

**Comment by sumppen** [comment]
Hi,

I’ve not been at my computer for a few days, but at least today I can send messages just fine.
$ ./runExample.sh 358xxxxxxxx 'LN/cdxxxxxxxxxx1QtSAGhsJA=' 'dnaprepaidtest' 'DNA PrePaid Too'
$ send
To: 358xxxxxxxxx
Message: Good morning! How are you today
Event send_message: phoneNumber=358xxxxxxxxx
message-1434951432-1
$ Event message_received_client: phoneNumber=358xxxxxxxxx,msgId=message-1434951432-1,from=358xxxxxxxxx@s.whatsapp.net,time=1434951478,type=
Event message_received_client: phoneNumber=358xxxxxxxxx,msgId=message-1434951432-1,from=358xxxxxxxxx@s.whatsapp.net,time=1434951478,type=read

**Comment by huchdadiya** [comment]
Hi,
   Thanks for your reply, but can you please check below that what am I doing wrong? beacuse I am not getting any code for registration.

First step:
java -cp target/dependency/*:target/whatsapi4j-1.0.1-SNAPSHOT.jar net.sumppen.whatsapi4j.example.ExampleApplication 91XXXXXXXXXX '' 'myapp' 'myappname'

It is working fine, and I am getting an ID.
After this, in console, I am trying to request for sending code.

$ request

but it got stuck, there is no response from whatsapp side, I am not receiving any sms.

I have checked  ping v.whatsapp.net
It is also working fine.

Please help me to sort out this.

Thanks in advance.
